// Comparison report generators for TXT and MD formats

export function generateComparisonTextReport(data: any): string {
  const { deck1Name, deck2Name, analysis } = data;
  
  const deck1 = analysis.deck1Analysis || {};
  const deck2 = analysis.deck2Analysis || {};
  const comparison = analysis.comparison || {};
  
  let report = '';
  
  report += '========================================\n';
  report += '   PITCH DECK COMPARISON REPORT\n';
  report += '========================================\n\n';
  
  report += `Deck 1: ${deck1Name}\n`;
  report += `Deck 2: ${deck2Name}\n`;
  report += `Generated: ${new Date().toLocaleString()}\n\n`;
  
  report += '========================================\n';
  report += '   OVERALL SCORES\n';
  report += '========================================\n\n';
  
  report += `Deck 1: ${deck1.overallScore || 0}/100\n`;
  report += `Deck 2: ${deck2.overallScore || 0}/100\n\n`;
  
  const winner = comparison.winnerOverall || 'tie';
  if (winner === 'deck1') {
    report += `Winner: ${deck1Name} is stronger overall\n\n`;
  } else if (winner === 'deck2') {
    report += `Winner: ${deck2Name} is stronger overall\n\n`;
  } else {
    report += `Winner: Both decks are equally strong\n\n`;
  }
  
  report += '========================================\n';
  report += '   EXECUTIVE SUMMARY\n';
  report += '========================================\n\n';
  
  report += `${comparison.summary || 'Comparison analysis complete.'}\n\n`;
  
  report += '========================================\n';
  report += '   CATEGORY COMPARISON\n';
  report += '========================================\n\n';
  
  const categories = comparison.categoryWinners || {};
  Object.entries(categories).forEach(([category, winner]) => {
    report += `${category.toUpperCase()}: `;
    if (winner === 'deck1') report += `${deck1Name} wins\n`;
    else if (winner === 'deck2') report += `${deck2Name} wins\n`;
    else report += `Tie\n`;
  });
  report += '\n';
  
  report += '========================================\n';
  report += '   STRENGTHS & WEAKNESSES\n';
  report += '========================================\n\n';
  
  report += `--- ${deck1Name} Strengths ---\n`;
  (comparison.strengths?.deck1 || []).forEach((s: string) => {
    report += `  ✓ ${s}\n`;
  });
  report += '\n';
  
  report += `--- ${deck1Name} Weaknesses ---\n`;
  (comparison.weaknesses?.deck1 || []).forEach((w: string) => {
    report += `  ⚠ ${w}\n`;
  });
  report += '\n';
  
  report += `--- ${deck2Name} Strengths ---\n`;
  (comparison.strengths?.deck2 || []).forEach((s: string) => {
    report += `  ✓ ${s}\n`;
  });
  report += '\n';
  
  report += `--- ${deck2Name} Weaknesses ---\n`;
  (comparison.weaknesses?.deck2 || []).forEach((w: string) => {
    report += `  ⚠ ${w}\n`;
  });
  report += '\n';
  
  report += '========================================\n';
  report += '   KEY DIFFERENCES\n';
  report += '========================================\n\n';
  
  (comparison.keyDifferences || []).forEach((diff: string, idx: number) => {
    report += `${idx + 1}. ${diff}\n`;
  });
  report += '\n';
  
  report += '========================================\n';
  report += '   RECOMMENDATIONS\n';
  report += '========================================\n\n';
  
  report += `--- For ${deck1Name} ---\n`;
  (comparison.recommendations?.deck1 || []).forEach((rec: string) => {
    report += `  → ${rec}\n`;
  });
  report += '\n';
  
  report += `--- For ${deck2Name} ---\n`;
  (comparison.recommendations?.deck2 || []).forEach((rec: string) => {
    report += `  → ${rec}\n`;
  });
  report += '\n';
  
  report += '========================================\n';
  report += 'Generated by Team SSO Intelligence\n';
  report += '========================================\n';
  
  return report;
}

export function generateComparisonMarkdownReport(data: any): string {
  const { deck1Name, deck2Name, analysis } = data;
  
  const deck1 = analysis.deck1Analysis || {};
  const deck2 = analysis.deck2Analysis || {};
  const comparison = analysis.comparison || {};
  
  let report = '';
  
  report += '# Pitch Deck Comparison Report\n\n';
  
  report += `**Deck 1:** ${deck1Name}  \n`;
  report += `**Deck 2:** ${deck2Name}  \n`;
  report += `**Generated:** ${new Date().toLocaleString()}\n\n`;
  
  report += '---\n\n';
  
  report += '## Overall Scores\n\n';
  
  report += `| Deck | Score |\n`;
  report += `|------|-------|\n`;
  report += `| ${deck1Name} | **${deck1.overallScore || 0}/100** |\n`;
  report += `| ${deck2Name} | **${deck2.overallScore || 0}/100** |\n\n`;
  
  const winner = comparison.winnerOverall || 'tie';
  if (winner === 'deck1') {
    report += `### 🏆 Winner: ${deck1Name} is stronger overall\n\n`;
  } else if (winner === 'deck2') {
    report += `### 🏆 Winner: ${deck2Name} is stronger overall\n\n`;
  } else {
    report += `### ⚖️ Both decks are equally strong\n\n`;
  }
  
  report += '---\n\n';
  
  report += '## Executive Summary\n\n';
  report += `${comparison.summary || 'Comparison analysis complete.'}\n\n`;
  
  report += '---\n\n';
  
  report += '## Category-by-Category Comparison\n\n';
  
  report += '| Category | Winner |\n';
  report += '|----------|--------|\n';
  const categories = comparison.categoryWinners || {};
  Object.entries(categories).forEach(([category, catWinner]) => {
    let winnerText = '';
    if (catWinner === 'deck1') winnerText = deck1Name;
    else if (catWinner === 'deck2') winnerText = deck2Name;
    else winnerText = 'Tie';
    report += `| ${category.charAt(0).toUpperCase() + category.slice(1)} | ${winnerText} |\n`;
  });
  report += '\n';
  
  report += '---\n\n';
  
  report += '## Strengths & Weaknesses\n\n';
  
  report += `### ${deck1Name}\n\n`;
  report += '#### ✅ Strengths\n\n';
  (comparison.strengths?.deck1 || []).forEach((s: string) => {
    report += `- ${s}\n`;
  });
  report += '\n';
  
  report += '#### ⚠️ Weaknesses\n\n';
  (comparison.weaknesses?.deck1 || []).forEach((w: string) => {
    report += `- ${w}\n`;
  });
  report += '\n';
  
  report += `### ${deck2Name}\n\n`;
  report += '#### ✅ Strengths\n\n';
  (comparison.strengths?.deck2 || []).forEach((s: string) => {
    report += `- ${s}\n`;
  });
  report += '\n';
  
  report += '#### ⚠️ Weaknesses\n\n';
  (comparison.weaknesses?.deck2 || []).forEach((w: string) => {
    report += `- ${w}\n`;
  });
  report += '\n';
  
  report += '---\n\n';
  
  report += '## Key Differences\n\n';
  
  (comparison.keyDifferences || []).forEach((diff: string, idx: number) => {
    report += `${idx + 1}. ${diff}\n`;
  });
  report += '\n';
  
  report += '---\n\n';
  
  report += '## Recommendations\n\n';
  
  report += `### For ${deck1Name}\n\n`;
  (comparison.recommendations?.deck1 || []).forEach((rec: string) => {
    report += `- ${rec}\n`;
  });
  report += '\n';
  
  report += `### For ${deck2Name}\n\n`;
  (comparison.recommendations?.deck2 || []).forEach((rec: string) => {
    report += `- ${rec}\n`;
  });
  report += '\n';
  
  report += '---\n\n';
  report += '*Generated by Team SSO Intelligence*\n';
  
  return report;
}
